apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oai-isolation

resources:
  - namespace.yaml
  - ../containers/gnb/crc/gnb-crc-deployment.yaml
  - ../containers/gnb/layer_map/gnb-layer-map-deployment.yaml
  - ../containers/gnb/ldpc/gnb-ldpc-deployment.yaml
  - ../containers/gnb/modulation/gnb-modulation-deployment.yaml
  - ../containers/gnb/ofdm_mod/gnb-ofdm-mod-deployment.yaml
  - ../containers/gnb/precoding/gnb-precoding-deployment.yaml
  - ../containers/gnb/scramble/gnb-scramble-deployment.yaml
  - ue-ch-est-deployment.yaml
  - ue-ch-mmse-deployment.yaml
  - ue-check-crc-deployment.yaml
  - ue-descrambling-deployment.yaml
  - ue-layer-demap-deployment.yaml
  - ue-ldpc-dec-deployment.yaml
  - ue-ofdm-demod-deployment.yaml
  - ue-soft-demod-deployment.yaml

labels:
  - pairs:
      project: oai-isolation
      managed-by: kustomize

commonAnnotations:
  description: "OAI Isolation microservices for 5G signal processing"
