apiVersion: v1
kind: Service
metadata:
  name: nr_crc
  namespace: oai-functions
  labels:
    app: nr_crc
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_crc
  ports:
  - port: 80
    targetPort: 8002
    protocol: TCP
    name: http
