apiVersion: v1
kind: Service
metadata:
  name: nr_crc_check
  namespace: oai-functions
  labels:
    app: nr_crc_check
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_crc_check
  ports:
  - port: 80
    targetPort: 8012
    protocol: TCP
    name: http
