apiVersion: v1
kind: Service
metadata:
  name: nr_descrambling
  namespace: oai-functions
  labels:
    app: nr_descrambling
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_descrambling
  ports:
  - port: 80
    targetPort: 8010
    protocol: TCP
    name: http
