apiVersion: v1
kind: Service
metadata:
  name: nr_ldpc
  namespace: oai-functions
  labels:
    app: nr_ldpc
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_ldpc
  ports:
  - port: 80
    targetPort: 8007
    protocol: TCP
    name: http
