apiVersion: v1
kind: Service
metadata:
  name: nr_ldpc_dec
  namespace: oai-functions
  labels:
    app: nr_ldpc_dec
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_ldpc_dec
  ports:
  - port: 80
    targetPort: 8015
    protocol: TCP
    name: http
