apiVersion: v1
kind: Service
metadata:
  name: nr_modulation_test
  namespace: oai-functions
  labels:
    app: nr_modulation_test
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_modulation_test
  ports:
  - port: 80
    targetPort: 8005
    protocol: TCP
    name: http
