apiVersion: v1
kind: Service
metadata:
  name: nr_mmse_eq
  namespace: oai-functions
  labels:
    app: nr_mmse_eq
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_mmse_eq
  ports:
  - port: 80
    targetPort: 8014
    protocol: TCP
    name: http
