apiVersion: v1
kind: Service
metadata:
  name: nr_ofdm_modulation
  namespace: oai-functions
  labels:
    app: nr_ofdm_modulation
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_ofdm_modulation
  ports:
  - port: 80
    targetPort: 8003
    protocol: TCP
    name: http
