apiVersion: v1
kind: Service
metadata:
  name: nr_ofdm_demo
  namespace: oai-functions
  labels:
    app: nr_ofdm_demo
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_ofdm_demo
  ports:
  - port: 80
    targetPort: 8008
    protocol: TCP
    name: http
