apiVersion: v1
kind: Service
metadata:
  name: nr_precoding
  namespace: oai-functions
  labels:
    app: nr_precoding
    component: oai-function
spec:
  type: ClusterIP
  selector:
    app: nr_precoding
  ports:
  - port: 80
    targetPort: 8004
    protocol: TCP
    name: http
